name: flutter_app_template
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: 7.3.2
  flutter_hooks: 0.18.6
  hooks_riverpod: 2.3.6
  flutter_riverpod: 2.3.6
  riverpod_annotation: 2.1.1
  freezed_annotation: 2.2.0 
  fast_immutable_collections: 9.1.3
  shared_preferences: 2.1.1
  auto_route_generator: 7.1.1

dev_dependencies: # flutter pub run build_runner watch --delete-conflicting-outputs
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  custom_lint: 0.4.0
  riverpod_lint: 1.3.2
  build_runner: 2.4.4
  freezed: 2.3.4
  riverpod_generator: 2.2.3

flutter:
  uses-material-design: true
